### ISSUE TITLE
{ $item } невидимые символы

### ISSUE THREAD

**Issue by Naturalov** [Arustinal/fluentogram#15]
используем условно такие конструкции
![изображение](https://github.com/Arustinal/fluentogram/assets/105550744/886c27fd-57b8-4457-a10a-ce8deb754f7e)
![изображение](https://github.com/Arustinal/fluentogram/assets/105550744/44daa855-fc9c-403c-b65d-4f21d3ef3122)

Но при копирование ⁨Новачок⁩ мы видим 
![изображение](https://github.com/Arustinal/fluentogram/assets/105550744/f84c2c04-df06-4ec7-b8b3-a9def63f9d47)

**Comment by affkie** [comment]
I think you should use English

**Comment by Naturalov** [comment]
> I think you should use English

In my locals or in issue?

**Comment by dsodx** [comment]
Конечно в ишью :)

**Comment by merura** [comment]
Check [last paragraph](https://projectfluent.org/python-fluent/fluent.runtime/stable/internals.html#using-fluentbundle)
You will notice the extra characters \u2068 and \u2069 in the output. These are Unicode bidi isolation characters that help to ensure that the interpolated strings are handled correctly in the situation where the text direction of the substitution might not match the text direction of the localized text. These characters can be disabled if you are sure that is not possible for your app by passing use_isolating=False to the FluentBundle constructor.

**Comment by Naturalov** [comment]
> Check [last paragraph](https://projectfluent.org/python-fluent/fluent.runtime/stable/internals.html#using-fluentbundle) You will notice the extra characters \u2068 and \u2069 in the output. These are Unicode bidi isolation characters that help to ensure that the interpolated strings are handled correctly in the situation where the text direction of the substitution might not match the text direction of the localized text. These characters can be disabled if you are sure that is not possible for your app by passing use_isolating=False to the FluentBundle constructor.

It works, thank you!

**Comment by Naturalov** [comment]
Thx
