### ISSUE TITLE
Python 3.12+ specific syntax is used

### ISSUE THREAD

**Issue by D-Sokol** [Arustinal/fluentogram#26]
With python 3.11 and older any import from `fluentogram==1.1.8` raises the following error:
```
  File "/home/skald/src/schedule/.venv/lib/python3.11/site-packages/fluentogram/src/impl/storages/__init__.py", line 1, in <module>
    from .nats_storage import NatsStorage
  File "/home/skald/src/schedule/.venv/lib/python3.11/site-packages/fluentogram/src/impl/storages/nats_storage.py", line 99
    subject = f'${stream_name.replace('_', self.separator, 1)}.>'
```
The reason is usage of single quotes inside of single-quoted f-string, what is 3.12+ feature. PyPi marks shows that 3.9 should be supported, so I believe this is a bug.

**Comment by Arustinal** [comment]
Check 1.1.9 release

**Comment by D-Sokol** [comment]
1.1.9 works for me with python 3.11, but still there are some patches required for 3.9 (I've used `docker run python:3.9-slim`):
```
import typing
import typing_extensions
typing.Self = typing_extensions.Self
typing.TypeAlias = typing_extensions.TypeAlias

import fluentogram
...  # other code
```
There weren't any troubles with simple examples after this hack in this container.

**Comment by D-Sokol** [comment]
https://github.com/Arustinal/fluentogram/pull/28

**Comment by Arustinal** [comment]
Merged
